import time 
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By 
from selenium.webdriver.support.ui import WebDriverWait
driver = webdriver.Chrome()
#driver.maximize_window()
driver.get("https://spaces.avayacloud.com/")
#Đăng nhập
elem = driver.find_element(By.NAME,('username'))
elem.clear()
elem.send_keys("nthedat@tma.com.vn")
elem = driver.find_element(By.ID,('GetStartedBtn'))
elem.click()
time.sleep(3)
elem = driver.find_element(By.NAME,("password"))
elem.clear()
elem.send_keys("Binhdinh#1997")
elem = driver.find_element(By.ID,("GetStartedBtn"))
elem.click()
time.sleep(3)
elem = driver.find_element(By.NAME,("continue"))
elem.click()
time.sleep(3)
#Test
elem = driver.find_element(By.CLASS_NAME,"global-header-logo-area")
elem.click()
time.sleep(2)
elem = driver.find_element(By.XPATH,"//input[@class = 'search-input']")
elem.send_keys("TranHuyenTrang")
time.sleep(3)
#Nếu có 
elem = driver.find_element(By.XPATH,"//span[contains(text(),'TranHuyenTrang')]")
elem.click()
time.sleep(2)
elem = driver.find_element(By.CLASS_NAME,'neo-icon-chevron-down')
elem.click()
time.sleep(2)
elem = driver.find_element(By.XPATH,"//span[contains(text(),'Edit space')]")
elem.click()
time.sleep(2)
elem = driver.find_element(By.XPATH,"//span[contains(text(),'Delete')]")
elem.click()
time.sleep(2)
elem = driver.find_element(By.XPATH,"//span[contains(text(),'Delete')]")
elem.click()
time.sleep(5)
driver.quit()